/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.java;

import javax.swing.JOptionPane;

/**
 *
 * @author Shreesha Mallatheru
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        searchBox = new javax.swing.JTextField();
        isbnSearchBtn = new javax.swing.JButton();
        searchResult = new javax.swing.JTextField();
        bookISBNbox = new javax.swing.JTextField();
        orderBtn = new javax.swing.JButton();
        nameInputBox = new javax.swing.JTextField();
        isbnInputBox = new javax.swing.JTextField();
        publisherInputBox = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        copiesInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        copierOrderInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameBtn = new javax.swing.JButton();
        publisherBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        isbnSearchBtn.setText("ISBN");
        isbnSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnSearchBtnActionPerformed(evt);
            }
        });

        searchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchResultActionPerformed(evt);
            }
        });

        bookISBNbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookISBNboxActionPerformed(evt);
            }
        });

        orderBtn.setText("ORDER");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        nameInputBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputBoxActionPerformed(evt);
            }
        });

        isbnInputBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnInputBoxActionPerformed(evt);
            }
        });

        publisherInputBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherInputBoxActionPerformed(evt);
            }
        });

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("NAME");

        jLabel3.setText("ISBN");

        jLabel4.setText("PUBLISHER");

        jLabel5.setText("ISBN");

        jLabel6.setText("Search");

        copiesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiesInputActionPerformed(evt);
            }
        });

        jLabel7.setText("COPIES");

        jLabel8.setText("COPIES");

        jLabel10.setText("UPDATE BOOK");

        jLabel11.setText("ORDER");

        jLabel12.setText("SEARCH");

        nameBtn.setText("NAME");
        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });

        publisherBtn.setText("PUBLISHER");
        publisherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("BOOK STORE");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(isbnSearchBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(publisherBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(searchBox)
                                    .addComponent(searchResult))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(orderBtn)
                                            .addComponent(bookISBNbox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(copierOrderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 95, Short.MAX_VALUE)
                                .addComponent(updateBtn))
                            .addComponent(publisherInputBox)
                            .addComponent(nameInputBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isbnInputBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(copiesInput)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(0, 112, Short.MAX_VALUE)))))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(144, 144, 144)
                .addComponent(jLabel10)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(isbnSearchBtn)
                                    .addComponent(nameBtn)
                                    .addComponent(publisherBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(copierOrderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(orderBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(searchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookISBNbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameInputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(isbnInputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(publisherInputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(copiesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void isbnSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnSearchBtnActionPerformed
        //ISBN Search button action
            
        //Reads the input from search box
        String inputIsbn = searchBox.getText();
        
        
        //Checks for empty input
        if(inputIsbn.length() == 0)
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up search box");
        else{
            

            /*





            Query to fetch the table content where isbn = inputIsbn from text box;




            */
            //Displays the result's to outputbox
            searchBox.setText("");
            searchResult.setText(inputIsbn);
        }
    }//GEN-LAST:event_isbnSearchBtnActionPerformed

    private void searchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchResultActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        
        //Stores the book ISBN entered in textbox to bookISBN variable
        String bookISBN = bookISBNbox.getText();
        String bookCopies = copierOrderInput.getText();
        
        //Checks for EMpty field
        if(bookISBN.length() == 0)
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up book ISBN");
        else if(bookCopies.length() == 0)
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up book copies");
        else{
            
        
        /*
        
        
        
        
            Query to order the input where isbn = bookISBN from input box and copies = bookCopies from copies input box
        
        
        
        
        */
        String result = "Book "+bookISBN+" is ordered"+bookCopies+" copies.\n";
        JOptionPane.showMessageDialog(null, result);
        //bookISBNResult.setText(bookISBN);
        bookISBNbox.setText("");
        copierOrderInput.setText("");
        }
    }//GEN-LAST:event_orderBtnActionPerformed

    
   
    private void bookISBNboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookISBNboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookISBNboxActionPerformed

    private void isbnInputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnInputBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnInputBoxActionPerformed

    private void nameInputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputBoxActionPerformed

    private void publisherInputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherInputBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherInputBoxActionPerformed

    
    
    
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
       
        //Stores the name entered in name input box to name
        String name = nameInputBox.getText();
        
        //Stores the isbn entered in isbn input box to isbn
        String isbn = isbnInputBox.getText();
        
        //Stores the author entered in author input box to author
        String publisher = publisherInputBox.getText();
        
        //Stores the no of copies in copies variable
        String copies = copiesInput.getText();
        
        /*
        
        
            Query to insert the data into table
        
            "insert into table_name values(isbn,name,publisher,copies);
        
            //using jdbc
        
        */
        
        
        
        //Alert box saying result
        
        String result = name+"\n"+isbn+"\n"+publisher+"\n"+copies+"\n";
            JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void copiesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiesInputActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        //Stores the book name entered in searchbox to name variable
        String inputName = searchBox.getText();
        
        
        //Checks for EMpty field
        if(inputName.length() == 0)
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up book name");
        else{ 
            /*




                Query to search from table where name = inputName given from input search box




            */
            searchResult.setText(inputName);
            searchBox.setText("");
        }
    }//GEN-LAST:event_nameBtnActionPerformed

    private void publisherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherBtnActionPerformed
          //Stores the book name entered in searchbox to name variable
        String inputPublisher = searchBox.getText();
        
        
        //Checks for EMpty field
        if(inputPublisher.length() == 0)
            JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up book name");
        else{ 
            /*




                Query to search from table where publisher = inputPublisher given from input search box




            */
            searchResult.setText(inputPublisher);
            searchBox.setText("");
        }
    }//GEN-LAST:event_publisherBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookISBNbox;
    private javax.swing.JTextField copierOrderInput;
    private javax.swing.JTextField copiesInput;
    private javax.swing.JTextField isbnInputBox;
    private javax.swing.JButton isbnSearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nameBtn;
    private javax.swing.JTextField nameInputBox;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton publisherBtn;
    private javax.swing.JTextField publisherInputBox;
    private javax.swing.JTextField searchBox;
    private javax.swing.JTextField searchResult;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
